### PR TITLE
Theme config

### PR DESCRIPTION
**Pull request by od-hunter**
@earrietadev kindly review

### CODE REVIEW

**Comment by earrietadev** [comment]
You're making `@creit.tech/stellar-wallets-kit` a dependency of the same `@creit.tech/stellar-wallets-kit` library and you are you creating a new StellarWalletsKit class on the modal, what's the reason for both?. 

You are also updating the root `body` styles, that will also affect websites using this library. Styles must update only this library's modal styles, nothing else. Styles are applied to a webcomponent made with Lit, you should only update that webcomponent.

**Comment by od-hunter** [comment]
Sir you closed the issue?

**Comment by od-hunter** [comment]
@earrietadev kindly review hopeully there's no more issues

**Comment by od-hunter** [comment]
@earrietadev please review

**Comment by earrietadev** [comment]
@od-hunter please stop spamming, I already reviewed this and you haven't addressed it.

**Pull request closed without merging**
